'?': false
allow_xla_at_inference: false
alsologtostderr: false
amp: false
anchor_scale: 8.0
aspect_ratios:
- !!python/tuple
  - 1.0
  - 1.0
- !!python/tuple
  - 1.4
  - 0.7
- !!python/tuple
  - 0.7
  - 1.4
augment_input_data: true
batch_size_per_im: 512
bbox_reg_weights: !!python/tuple
- 10.0
- 10.0
- 5.0
- 5.0
bg_thresh_hi: 0.5
bg_thresh_lo: 0.0
checkpoint: ./weights/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603
data_dir: null
eval_after_training: false
eval_batch_size: 8
eval_samples: 5000
fast_rcnn_box_loss_weight: 1.0
fast_rcnn_mlp_head_dim: 1024
fg_fraction: 0.25
fg_thresh: 0.5
finetune_bn: false
global_gradient_clip_ratio: -1.0
gt_mask_size: 112
help: false
helpfull: false
helpshort: false
helpxml: false
image_size: !!python/tuple
- 832
- 1344
include_groundtruth_in_features: false
include_mask: true
init_learning_rate: 0.04
l2_weight_decay: 0.0001
learning_rate_decay_levels:
- 0.1
- 0.01
learning_rate_levels:
- 0.004
- 0.0004
learning_rate_steps:
- 480000
- 640000
log_dir: ''
log_path: ./mrcnn.json
logtostderr: false
max_level: 6
min_level: 2
mode: train
model_dir: ./weights
momentum: 0.9
mrcnn_resolution: 28
mrcnn_weight_loss_mask: 1.0
num_classes: 91
num_scales: 1
num_steps_per_eval: 2500
only_check_args: false
op_conversion_fallback_to_while_loop: false
pdb_post_mortem: false
profile_file: null
report_frequency: null
rpn_batch_size_per_im: 256
rpn_box_loss_weight: 1.0
rpn_fg_fraction: 0.5
rpn_min_size: 0.0
rpn_negative_overlap: 0.3
rpn_positive_overlap: 0.7
run_with_pdb: false
run_with_profiling: false
save_checkpoints_steps: 2500
seed: null
showprefixforinfo: true
skip_checkpoint_variables: ^NO_SKIP$
skip_crowd_during_training: true
stderrthreshold: fatal
test_detections_per_image: 100
test_nms: 0.5
test_random_seed: 301
test_randomize_ordering_seed: ''
test_rpn_nms_thresh: 0.7
test_rpn_post_nms_topn: 1000
test_rpn_pre_nms_topn: 1000
test_srcdir: ''
test_tmpdir: /tmp/absl_testing
total_steps: 20000
train_batch_size: 2
train_rpn_nms_threshold: 0.7
train_rpn_post_nms_topn: 1000
train_rpn_pre_nms_topn: 2000
training_file_pattern: ./data_dir/train*.tfrecord
use_batched_nms: true
use_category: true
use_cprofile_for_profiling: true
use_custom_box_proposals_op: false
use_fake_data: false
use_tf_distributed: false
v: 0
val_json_file: ''
validation_file_pattern: ''
verbosity: 0
visualize_images_summary: false
warmup_learning_rate: 0.0
warmup_steps: 1000
xla: true
xml_output_file: ''
